all:
	# gcc -o sum sum.c list.c
	# gcc -o in in.c list.c
	# gcc -o size size.c list.c
	# gcc -o position position.c list.c
	# gcc -o merge merge.c list.c
	# gcc -o sudoku sudoku.c
	# gcc -o insert insert.c list.c
	gcc -o copy copy.c list.c
clean:
	rm sum in size position merge sudoku insert copy
